user nginx;

worker_processes auto;

error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
    worker_connections 768;
}

http {
    map $host $site_root {
        cats.example.local /var/www/cat-site;
        dogs.example.local /var/www/dog-site;
    }

    map $host $api_backend {
        cats.example.local http://192.168.0.20:8080;
        dogs.example.local http://192.168.0.20:8081;
    }

    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;

    server_tokens off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    access_log /var/log/nginx/access.log;

    gzip on;

    include /etc/nginx/conf.d/*.conf;
}
