services:
  postgres:
    image: postgres:16
    container_name: postgres-cat-dog

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - /opt/my-db/postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  cat-api:
    build:
      context: ./cat-api

    container_name: cat-api

    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      API_ADDR: ":8080"

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

  dog-api:
    build:
      context: ./dog-api

    container_name: dog-api

    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      API_ADDR: ":8081"

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8081:8081"
